h seek -5                # h 向左快退 5 秒
l seek 5                 # l 向右快进 5 秒
j add volume -2          # j 音量减少
k add volume 2           # k 音量增加

# 播放控制
space cycle pause        # 空格键：暂停/播放
q quit                   # q：退出 mpv
Q quit-watch-later       # Q：退出并保存播放进度
f cycle fullscreen       # f：全屏切换
T cycle ontop            # T：切换窗口置顶

# 播放速度调整
] add speed 0.1          # ]：加速播放
[ add speed -0.1         # [：减速播放


