[edit]
    command = "nvim"
[diff]
    command = "delta"
    pager = "delta"
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
[data]
    email = "Wu-Felix@outlook.com"
    name = "felix"
